# Generated by Django 5.2.8 on 2025-11-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identite', models.CharField(max_length=255)),
                ('village_quartier', models.CharField(max_length=255)),
                ('numero_menage', models.CharField(max_length=50)),
                ('date_enquete', models.DateField()),
                ('nom_enqueteur', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('score_total', models.IntegerField(default=0)),
                ('niveau_vulnerabilite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_question', models.CharField(max_length=10)),
                ('choix', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='application.menage')),
            ],
        ),
    ]
