# Generated by Django 5.2.8 on 2025-11-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('poids', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='code_question',
        ),
        migrations.AlterField(
            model_name='menage',
            name='niveau_vulnerabilite',
            field=models.CharField(choices=[('Très vulnérable', 'Très vulnérable'), ('Vulnérable', 'Vulnérable'), ('Moins vulnérable', 'Moins vulnérable')], default='*Moins vulnérable', max_length=50),
        ),
        migrations.AddField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.question'),
        ),
    ]
