# Generated by Django 5.2.8 on 2025-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_question_remove_reponse_code_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='air_sante',
            field=models.CharField(blank=True, choices=[('Bon', 'Bon')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menage',
            name='niveau_vulnerabilite',
            field=models.CharField(choices=[('Yalosase', 'Yalosase'), ('Lilanda', 'Lilanda'), ('Baonga', 'Baonga'), ('Yabasabola', 'Yabasabola'), ('Yasanga', 'Yasanga'), ('Yakosanga', 'Yakosanga'), ('Yafunga', 'Yafunga'), ('Lomboto', 'Lomboto'), ('Yabongengo', 'Yabongengo'), ('Yaelomba', 'Yaelomba')], max_length=50),
        ),
    ]
