# Generated by Django 5.2.8 on 2025-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_menage_air_sante_alter_menage_niveau_vulnerabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
    ]
