# Generated by Django 5.2.8 on 2025-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_menage_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menage',
            name='air_sante',
            field=models.CharField(blank=True, choices=[('Yalosase', 'Yalosase'), ('Lilanda', 'Lilanda'), ('Baonga', 'Baonga'), ('Yabasabola', 'Yabasabola'), ('Yasanga', 'Yasanga'), ('Yakosanga', 'Yakosanga'), ('Yafunga', 'Yafunga'), ('Lomboto', 'Lomboto'), ('Yabongengo', 'Yabongengo'), ('Yaelomba', 'Yaelomba')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menage',
            name='niveau_vulnerabilite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
