# Generated by Django 5.2.8 on 2025-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_menage_air_sante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='menage_images/'),
        ),
    ]
