# Generated by Django 5.2.8 on 2025-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_menage_niveau_vulnerabilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='niveau_vulnerabilite',
            field=models.CharField(blank=True, choices=[('Très vulnérable', 'Très vulnérable'), ('Vulnérable', 'Vulnérable'), ('Moins vulnérable', 'Moins vulnérable')], default='Moins vulnérable', max_length=50, null=True),
        ),
    ]
