# Generated by Django 5.2.8 on 2025-12-02 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_menage_niveau_vulnerabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='menage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
