# Generated by Django 5.2.8 on 2025-12-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_menage_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOffert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_offerts', to='application.menage')),
            ],
        ),
    ]
