# Generated by Django 5.2.8 on 2025-12-05 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_articleoffert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='menage',
            name='numero_menage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menage_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('fournisseurid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_fournies', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='offres', to='application.articles')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleOffert',
        ),
    ]
