# Generated by Django 5.2.8 on 2025-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_articles_alter_menage_numero_menage_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='menage_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
