# Generated by Django 5.2.8 on 2025-12-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_distribution_menage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='quantite',
        ),
    ]
