# Generated by Django 5.2.8 on 2025-12-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_articles_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.articles')),
                ('menage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='application.menage')),
            ],
        ),
        migrations.AlterField(
            model_name='distribution',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='offres', to='application.besoin'),
        ),
    ]
