# Generated by Django 5.2.8 on 2025-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_besoin_alter_distribution_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='menage',
        ),
        migrations.CreateModel(
            name='Bouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[(1, 'Très vulnérable'), (2, 'Vulnérable'), (3, 'Moins vulnérable')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('besoins', models.ManyToManyField(related_name='bouquets', to='application.besoin')),
            ],
        ),
        migrations.AlterField(
            model_name='distribution',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='offres', to='application.bouquets'),
        ),
    ]
