# Generated by Django 5.2.8 on 2025-12-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_remove_besoin_menage_bouquets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='items',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='menage_uuid',
        ),
        migrations.AddField(
            model_name='distribution',
            name='menage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='application.menage'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='date_distribution',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ItemDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_distributions', to='application.distribution')),
            ],
        ),
    ]
